version: "3"

services:

  httpd:
    image: alterway/httpd-prestashop:latest
    volumes:
      - "prestashop:/var/www/"
    env_file:
      - env/apache.env
      - env/php-fpm.env
    ports:
      - 80:80
    networks:
      - mysql-net
  php:
    image: alterway/prestashop-php:5.6-fpm
    volumes:
      - prestashop:/var/www/
    env_file:
      - env/php.env
      - env/mysql.env
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - DOMAIN=demo.local
      - VIRTUAL_HOST=${SHOPNAME}.demo.local
    networks:
      - mysql-net

  phpcli:
    image: alterway/prestashop-php:5.6-cli
    volumes:
      - prestashop:/var/www/
    env_file:
      - env/php.env
      - env/mysql.env
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - DOMAIN=demo.local
      - VIRTUAL_HOST=${SHOPNAME}.demo.local
    entrypoint : /bin/bash -xc "sleep 60 ; /entrypoint.sh /var/www/install/index_cli.php --domain=${SHOPNAME}.demo.local --db_server=${MYSQL_HOST} --db_name=${MYSQL_DATABASE} --db_user=${MYSQL_USER} --db_password=${MYSQL_PASSWORD} --firstname=${PRESTASHOP_FIRSTNAME} --lastname=${PRESTASHOP_LASTNAME} --password=${PRESTASHOP_PASSWORD} --email=${PRESTASHOP_EMAIL} --newsletter=0 --send_email=0 ;  chmod -R a+rw /var/www ; rm -rf /var/www/install"
    networks:
      - mysql-net
    depends_on:
      - php
      - mysql

  mysql-master:
    image: bitnami/mysql:latest
    ports:
      - 3306
    volumes:
      - lib_mysql:/bitnami/mysql
    environment:
      - MYSQL_REPLICATION_MODE=master

      - MYSQL_REPLICATION_USER
      - MYSQL_REPLICATION_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - "constraint:node==$NODE1"
    networks:
      - mysql-net

  mysql-slave:
    image: bitnami/mysql:latest
    ports:
      - 3306
    volumes:
      - lib_mysql:/bitnami/mysql
    depends_on:
      - mysql-master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER
      - MYSQL_REPLICATION_PASSWORD

      - MYSQL_MASTER_HOST=mysql-master
      - MYSQL_MASTER_PORT=3306
      - MYSQL_MASTER_USER=prestashop
      - MYSQL_MASTER_PASSWORD=pr3stash0p

      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - "constraint:node==$NODE2"
    networks:
      - mysql-net

  #varnish:
  #  image: alterway/varnish:4.0
  # ports:
  #    - 80:80
  #  environment:
  #    CACHE_SIZE: '1G'
  #    SERVICE_80_NAME: "${SHOPNAME}"
  #    SERVICE_80_TAGS: 'http'
  #    BACKEND_PORT_80_TCP_PORT: "80"
  #    BACKEND_PORT_80_TCP_ADDR: "httpd"
  #  depends_on:
  #     - httpd
  #  networks:
  #    - mysql-net

volumes:
  lib_mysql:
    driver: local
  prestashop:
    driver: local

networks:
  mysql-net:
    driver: overlay



